services:
  app:
    build: .
    container_name: hypervel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9501:9501"
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx-hypervel
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis-hypervel
    ports:
      - "6380:6379"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-hypervel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hypervel
      MYSQL_USER: hypervel
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge